services:
  frontend:
    build: ./src/forgetful_gardner/frontend
    ports:
      - "8000:8000"
    depends_on:
      - backend
    networks:
      - backend-network
    env_file:
      - .env

  backend:
    build: ./src/forgetful_gardner/backend
    ports:
      - "8001:8001"
    depends_on:
      - ollama
    networks:
      - backend-network
    env_file:
      - .env
    environment:
      OLLAMA_MODEL: "${OLLAMA_MODEL}"

  ollama:
    build: ./src/forgetful_gardner/llm_runner
    ports:
      - "11434:11434"
    container_name: ollama
    env_file:
      - .env
    environment:
      - OLLAMA_MODEL=${OLLAMA_MODEL}
    networks:
      - backend-network
    volumes:
      - ollama-data:/root/.ollama

networks:
  backend-network:
    driver: bridge

volumes:
  ollama-data:
